### ISSUE TITLE
Socratic Seminar #21 Topics

### ISSUE THREAD

**Issue by AndySchroder** [NashBitDevs/nashbitdevs.org#33] opened 2024-07-10 06:30 UTC
Tuesday, July 23rd, 2024

Add comments below to add or comment on topics See also ["Where to Find Topics for Future Seminars"](https://nashbitdevs.org/about/find-topics/).

Categories:

- Events
- News
- New Work/Research
- Bitcoin Projects
- Lightning Projects

**Comment by AndySchroder** [comment] 2024-07-10 06:30
https://spacesprotocol.org/paper/

**Comment by notmandatory** [comment] 2024-07-13 01:48
Lightning Projects

* [New BOLT12 page](https://bolt12.org/)
* [Phoenix Android/iOS/Server now supports BOLT12](https://x.com/PhoenixWallet/status/1808547081214439494)

**Comment by notmandatory** [comment] 2024-07-13 15:39
News 

* BIP 353 Resolver https://satsto.me/

**Comment by econoalchemist** [comment] 2024-07-13 21:21
News

- Samourai Wallet developments index: https://freesamourai.com/
- Tdev updates: https://x.com/frankcorva/status/1811093896144785625
- Is Google an unindicted co-conspirator?:https://www.therage.co/william-hill-release-on-bail/
- Bitcoin24 FREESAMOURAI panel, Friday July 26 at 14:00 on the Open Source stage: https://b.tc/conference/2024/agenda
- Support the Samourai Wallet defense fund: https://p2prights.org

**Comment by reez** [comment] 2024-07-15 20:06
**News**
- [OpenSats Fifth Wave of Bitcoin Grants](https://opensats.org/blog/bitcoin-grants-july-2024)
- [Announcing the OpenSats Education Initiative](https://opensats.org/blog/announcing-the-opensats-education-initiative)

**Bitcoin**
- New [Bitcoin Core Security Advisories](https://bitcoincore.org/en/security-advisories/) page
- [Block+Core Scientific](https://www.mining.build/blog/first-mining-chip-customer/)

**Comment by notmandatory** [comment] 2024-07-15 22:52
Research

- [High bandwidth Tor network fork. Incentivized by the Bitcoin Lightning Network.](https://devpost.com/software/el-tor)

**Comment by EthnTuttle** [comment] 2024-07-18 09:46
[Auditing Hashrate](https://github.com/stratum-mining/stratum/discussions/1052)

**Comment by notmandatory** [comment] 2024-07-18 20:57
Research

- [@vostrnad](https://stacker.news/vostrnad) ["Definitive explanation of my weird Bitcoin transaction"](https://stacker.news/items/600187)

**Comment by notmandatory** [comment] 2024-07-19 05:02
We're a little light on LN stuff so I'm adding:

- [LDK Node 0.3.0 release](https://github.com/lightningdevkit/ldk-node/blob/main/CHANGELOG.md)

**Comment by reez** [comment] 2024-07-19 13:59
> We're a little light on LN stuff so I'm adding:
> 
> * [LDK Node 0.3.0 release](https://github.com/lightningdevkit/ldk-node/blob/main/CHANGELOG.md)

If you can add a sub bullet to this for...
- [Add BIP21 Unified QR Code Support](https://github.com/lightningdevkit/ldk-node/pull/302)
... its a good PR just merged into `main` for LDK Node to touch on real quick

**Comment by reez** [comment] 2024-07-19 14:01
**News**
- [mempool.space accelerator](https://mempool.space/accelerator) available

**Comment by horologger** [comment] 2024-07-19 15:43
How about a discussion of DID schemes that use Bitcoin blockchain as the storage?  How being slow and costly be a feature not a bug(Softwar).

**Comment by reez** [comment] 2024-07-19 16:17
> How about a discussion of DID schemes that use Bitcoin blockchain as the storage? How could being slow and costly be considered a feature and not a bug(Softwar)?

would love to, if you could add a link for that topic to kick the discussion off then I'll add it to our topics list 👍

**Comment by reez** [comment] 2024-07-19 20:00
**Lightning**
- [Fedimint DNS Tracking Issue for Guardian API Endpoint Rotation](https://github.com/fedimint/fedimint/issues/5525)

**Comment by horologger** [comment] 2024-07-29 15:19
Hi Matthew,

I was late getting to Bitcoin Park on Thuesday(construction/rain in Chattanooga) but had a great time chatting with folks and later rolling over to the Moxy. Sorry I missed introducing myself directly.

On the DID topic, my local meetup here in Atlanta is now holding a monthly topic on DID and would love to collaborate with interested folks in Nashville.

Pop me a txt at 404-416-5688 and we can pick up the discussion. This email address was just a way to put some distance between me and the open source initiatives so I don't monitor it closely.

Sent with [Proton Mail](https://proton.me/) secure email.

**Closed** 2024-08-04 20:06 UTC
